// onedrive
var playlist = [{
    title: "你还要我怎样",
    artist: "于沃冉",
    mp3: "https://onedrive.lightly.ml/api?path=/music/memory/%E4%BD%A0%E8%BF%98%E8%A6%81%E6%88%91%E6%80%8E%E6%A0%B7_%E4%BA%8E.m4a&raw=true",
    cover: "player/img/你还要我怎样.jpg"
}, {
    title: "刚刚好",
    artist: "于沃冉",
    mp3: "https://onedrive.lightly.ml/api?path=/music/memory/%E5%88%9A%E5%88%9A%E5%A5%BD_%E4%BA%8E.m4a&raw=true",
    cover: "player/img/刚刚好.jpg"
}, {
    title: "刚刚好",
    artist: "合唱",
    mp3: "https://onedrive.lightly.ml/api?path=/music/memory/%E5%88%9A%E5%88%9A%E5%A5%BD_%E5%90%88.m4a&raw=true",
    cover: "player/img/刚刚好.jpg"
}, {
    title: "去流浪",
    artist: "合唱",
    mp3: "https://onedrive.lightly.ml/api?path=/music/memory/%E5%8E%BB%E6%B5%81%E6%B5%AA_%E5%8E%9F%E5%94%B1.m4a&raw=true",
    cover: "player/img/去流浪.jpg"
}, {
    title: "情侣装",
    artist: "于皮合",
    mp3: "https://onedrive.lightly.ml/api?path=/music/memory/%E6%83%85%E4%BE%A3%E8%A3%85_%E4%BA%8E%E7%9A%AE%E5%90%88.m4a&raw=true",
    cover: "player/img/情侣装.jpg"
}, {
    title: "意外",
    artist: "于王封合_贾狗叫",
    mp3: "https://onedrive.lightly.ml/api?path=/music/memory/%E6%84%8F%E5%A4%96_%E4%BA%8E%E7%8E%8B%E5%B0%81%E5%90%88_%E8%B4%BE%E7%8B%97%E5%8F%AB.m4a&raw=true",
    cover: "player/img/意外.jpg"
}, {
    title: "暧昧",
    artist: "于沃冉",
    mp3: "https://onedrive.lightly.ml/api?path=/music/memory/%E6%9A%A7%E6%98%A7_%E4%BA%8E.m4a&raw=true",
    cover: "player/img/暧昧.jpg"
}, {
    title: "暧昧",
    artist: "合唱",
    mp3: "https://onedrive.lightly.ml/api?path=/music/memory/%E6%9A%A7%E6%98%A7_%E5%90%88.m4a&raw=true",
    cover: "player/img/暧昧.jpg"
}, {
    title: "有何不可",
    artist: "于皮贾合",
    mp3: "https://onedrive.lightly.ml/api?path=/music/memory/%E6%9C%89%E4%BD%95%E4%B8%8D%E5%8F%AF_%E4%BA%8E%E7%9A%AE%E8%B4%BE.m4a&raw=true",
    cover: "player/img/有何不可.jpg"
}, {
    title: "未知",
    artist: "贾皮合",
    mp3: "https://onedrive.lightly.ml/api?path=/music/memory/%E6%9C%AA%E7%9F%A5_%E8%B4%BE%E7%9A%AE%E5%90%88.m4a&raw=true",
    cover: "player/img/未知.jpg"
}, {
    title: "江湖",
    artist: "于皮合",
    mp3: "https://onedrive.lightly.ml/api?path=/music/memory/%E6%B1%9F%E6%B9%96_%E5%8E%9F%E5%94%B1.m4a&raw=true",
    cover: "player/img/江湖.jpg"
}, {
    title: "爱情转移",
    artist: "贾于封合",
    mp3: "https://onedrive.lightly.ml/api?path=/music/memory/%E7%88%B1%E6%83%85%E8%BD%AC%E7%A7%BB_%E8%B4%BE%E4%BA%8E%E5%B0%81.m4a&raw=true",
    cover: "player/img/爱情转移.jpg"
}, {
    title: "说谎",
    artist: "于王合",
    mp3: "https://onedrive.lightly.ml/api?path=/music/memory/%E8%AF%B4%E8%B0%8E_%E4%BA%8E%E7%8E%8B.m4a&raw=true",
    cover: "player/img/说谎.jpg"
}, {
    title: "预谋",
    artist: "贾皮合",
    mp3: "https://onedrive.lightly.ml/api?path=/music/memory/%E9%A2%84%E8%B0%8B_%E8%B4%BE%E7%9A%AE%E5%90%88.m4a&raw=true",
    cover: "player/img/预谋.jpg"
}, {
    title: "风云诀",
    artist: "于王合",
    mp3: "https://onedrive.lightly.ml/api?path=/music/memory/%E9%A3%8E%E4%BA%91%E5%86%B3_%E4%BA%8E%E7%8E%8B.m4a&raw=true",
    cover: "player/img/风云诀.jpg"
}, {
    title: "认错",
    artist: "合唱",
    mp3: "https://onedrive.lightly.ml/api?path=/music/memory/%E8%AE%A4%E9%94%99_%E5%90%88.m4a&raw=true",
    cover: "player/img/认错.jpg"
},{
    title: "起风了",
    artist: "买辣椒也用券",
    mp3: "https://music.163.com/song/media/outer/url?id=1330348068.mp3",
    cover: "player/img/109951163699673355.jpg",
},{
    title: "7 years",
    artist: "Lukas",
    mp3: "https://onedrive.lightly.ml/api?path=/music/7%20Years%20Lukas%20Graham.mp3&raw=true",
    cover: "player/img/3275445140690155.jpg"
}];
// 蓝奏
var playlist = [{
    title: "你还要我怎样",
    artist: "于沃冉",
    mp3: "https://easul.freecluster.eu/lanzou.php?url=https://www.lanzout.com/iU1pl06x3zad&pwd=1111&type=GET_URL",
    cover: "player/img/你还要我怎样.jpg"
}, {
    title: "刚刚好",
    artist: "于沃冉",
    mp3: "https://easul.freecluster.eu/lanzou.php?url=https://www.lanzout.com/ioNez06x3ytg&pwd=1111&type=GET_URL",
    cover: "player/img/刚刚好.jpg"
}, {
    title: "刚刚好",
    artist: "合唱",
    mp3: "https://easul.freecluster.eu/lanzou.php?url=https://www.lanzout.com/iwx0m06x3yob&pwd=1111&type=GET_URL",
    cover: "player/img/刚刚好.jpg"
}, {
    title: "去流浪",
    artist: "合唱",
    mp3: "https://easul.freecluster.eu/lanzou.php?url=https://www.lanzout.com/id53J06x3yli&pwd=1111&type=GET_URL",
    cover: "player/img/去流浪.jpg"
}, {
    title: "情侣装",
    artist: "于皮合",
    mp3: "https://easul.freecluster.eu/lanzou.php?url=https://www.lanzout.com/iauuJ06x3yif&pwd=1111&type=GET_URL",
    cover: "player/img/情侣装.jpg"
}, {
    title: "意外",
    artist: "于王封合_贾狗叫",
    mp3: "https://easul.freecluster.eu/lanzou.php?url=https://www.lanzout.com/iOaBv06x3z4h&pwd=1111&type=GET_URL",
    cover: "player/img/意外.jpg"
}, {
    title: "暧昧",
    artist: "于沃冉",
    mp3: "https://easul.freecluster.eu/lanzou.php?url=https://www.lanzout.com/itCVU06x3z3g&pwd=1111&type=GET_URL",
    cover: "player/img/暧昧.jpg"
}, {
    title: "暧昧",
    artist: "合唱",
    mp3: "https://easul.freecluster.eu/lanzou.php?url=https://www.lanzout.com/iszKQ06x3yna&pwd=1111&type=GET_URL",
    cover: "player/img/暧昧.jpg"
}, {
    title: "有何不可",
    artist: "于皮贾合",
    mp3: "https://easul.freecluster.eu/lanzou.php?url=https://www.lanzout.com/i9dI906x3yuh&pwd=1111&type=GET_URL",
    cover: "player/img/有何不可.jpg"
}, {
    title: "未知",
    artist: "贾皮合",
    mp3: "https://easul.freecluster.eu/lanzou.php?url=https://www.lanzout.com/iyS5H06x3yre&pwd=1111&type=GET_URL",
    cover: "player/img/未知.jpg"
}, {
    title: "江湖",
    artist: "于皮合",
    mp3: "https://easul.freecluster.eu/lanzou.php?url=https://www.lanzout.com/iAeCw06x3z9c&pwd=1111&type=GET_URL",
    cover: "player/img/江湖.jpg"
}, {
    title: "爱情转移",
    artist: "贾于封合",
    mp3: "https://easul.freecluster.eu/lanzou.php?url=https://www.lanzout.com/ibVxL06xzcxa&pwd=1111&type=GET_URL",
    cover: "player/img/爱情转移.jpg"
}, {
    title: "说谎",
    artist: "于王合",
    mp3: "https://easul.freecluster.eu/lanzou.php?url=https://www.lanzout.com/ixnPo06x3z8b&pwd=1111&type=GET_URL",
    cover: "player/img/说谎.jpg"
}, {
    title: "预谋",
    artist: "贾皮合",
    mp3: "https://easul.freecluster.eu/lanzou.php?url=https://www.lanzout.com/in3EM06x3yjg&pwd=1111&type=GET_URL",
    cover: "player/img/预谋.jpg"
}, {
    title: "风云诀",
    artist: "于王合",
    mp3: "https://easul.freecluster.eu/lanzou.php?url=https://www.lanzout.com/iNiSp06x3z0d&pwd=1111&type=GET_URL",
    cover: "player/img/风云诀.jpg"
}, {
    title: "认错",
    artist: "合唱",
    mp3: "https://easul.freecluster.eu/lanzou.php?url=https://www.lanzout.com/iHSoW06x3z1e&pwd=1111&type=GET_URL",
    cover: "player/img/认错.jpg"
},{
    title: "起风了",
    artist: "买辣椒也用券",
    mp3: "https://music.163.com/song/media/outer/url?id=1330348068.mp3",
    cover: "player/img/109951163699673355.jpg",
},{
    title: "7 years",
    artist: "Lukas",
    mp3: "https://onedrive.lightly.ml/api?path=/music/7%20Years%20Lukas%20Graham.mp3&raw=true",
    cover: "player/img/3275445140690155.jpg"
}];